project:
  type: website
  output-dir: docs

website:
  title: "L'Attestation"
  site-url: "https://l-attestation.github.io/"
  cookie-consent: true
  google-analytics: "G-9P56MCMK2Z"
  page-navigation: true
  favicon: COUV_ATTESTATION_PROMO_VOLUME.jpg
  open-graph: true
  # page-footer: "Théo Boulakia et Nicolas Mariot, avec [Quarto](https://quarto.org)"
  navbar:
    logo: COUV_ATTESTATION_PROMO_VOLUME.jpg
    left:
      - href: index.qmd
        text: Accueil
      - tables.qmd  
      - films.qmd
      - sources-francaises.qmd
      - donnees-mondiales.qmd
      - exercices.qmd
      - bibliographie.qmd

format:
  html:
    theme: cosmo
    linkcolor: "#E12634"
    css: styles.css
    toc: true
    
bibliography: references.json
lang: fr
