project:
  type: website
  output-dir: docs

website:
  title: "L'Attestation"
  site-url: "https://l-attestation.github.io/"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - text: "Mode d'emploi"
        file: mode-d-emploi.qmd
      - text: "Silence"
        file: silence.qmd
      - text: "Sources"
        file: sources.qmd
      - text: "Exercices"
        file: exercices.qmd
      - text: "Bibliographie"
        file: biblio.qmd

  sidebar: 
    - title: "Sources"
      style: docked
      background: light
      contents: sources
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
bibliography: references.json
lang: fr


