project:
  type: website
  output-dir: docs

website:
  title: "L'Attestation"
  site-url: "https://l-attestation.github.io/"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - mode-d-emploi.qmd
      - sources-francaises.qmd
      - donnees-mondiales.qmd
      - exercices.qmd
      - bibliographie.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
bibliography: references.json
lang: fr
