---
title: "À propos"
---

## Les auteurs

**Théo Boulakia** est normalien, doctorant en sociologie (École normale supérieure, Centre Maurice Halbwachs). Ses recherches, qui combinent méthodes ethnographiques et statistiques, portent sur l'élevage, la santé au travail et la surveillance de masse.

**Nicolas Mariot** est historien et sociologue, directeur de recherche au Centre européen de sociologie et de science politique (CNRS, EHESS et université Paris 1-Panthéon Sorbonne). Les notions d'obéissance et de conformisme sont depuis longtemps au coeur de son travail. Il fait partie du comité de pilotage du projet ANR « La vie en confinement » (Vico), dont les données constituent une partie du matériau utilisé dans ce livre. Il est l'auteur de nombreux ouvrages, parmi lesquels : *Intellectuels empêchés. Ou comment penser dans l'épreuve* (dir. avec Brigitte Gaïti, ENS Éditions, 2021), *Histoire d'un sacrifice. Robert, Alice et la guerre* (Seuil, 2017), *Tous unis dans la tranchée ? 1914-1918, les intellectuels rencontrent le peuple* (Seuil, 2013) ou *Face à la persécution. 991 Juifs dans la guerre* (avec Claire Zalc, Odile Jacob, 2010).

## Presse

### Mediapart

> *L'Attestation* renouvelle enfin les banalités éditées que l'on a pu lire sur le confinement. La matière des deux chercheurs repose sur de nombreuses sources allant des données Google aux coupures de presse, mais se fonde beaucoup sur l'étude Vico (« La vie en confinement »), enquête par questionnaire lancée entre le 15 avril et le 11 mai 2020, à laquelle 16 000 personnes répondirent et dont plus de 3 000 ajoutèrent des commentaires personnels sur l'expérience qu'ils étaient en train de vivre. Mais c'est leur angle qui suscite le plus d'intérêt : analyser à partir d'une expérience grandeur nature, une « expérience d'obéissance de masse largement inédite » et des questions « en général laissées aux exégètes abstraites de la philosophie politique ». Parmi ces interrogations fondamentales : à quelles conditions accepte-t-on de se soumettre aux autorités ? Quel doit être l'équilibre entre responsabilité et coercition dans la gestion des populations par un État ? Jusqu'où la limitation des libertés individuelles est-elle acceptable en régime démocratique ? Conscients que les réponses à ces questions diffèrent selon les individus et les expériences du confinement, les deux chercheurs proposent un livre à la fois fondé scientifiquement, mais dont l'écriture -- qui assume une dimension personnelle et quelques nuances d'incertitude voire d'ironie -- s'attache à ne braquer a priori personne sur un sujet très clivant. -- [**Joseph Confavreux**](https://www.mediapart.fr/journal/culture-et-idees/071023/pourquoi-avons-nous-obei-des-chercheurs-decryptent-le-confinement)

### Le Monde

[Entretien](https://www.lemonde.fr/idees/article/2023/11/06/le-covid-19-trois-ans-apres-avec-l-attestation-de-sortie-en-france-il-y-a-eu-une-forme-de-suivisme_6198467_3232.html) paru le 7 novembre 2023.
