---
title: "Auteurs"
---

**Théo Boulakia** est normalien, doctorant en sociologie (École normale supérieure, Centre Maurice Halbwachs). Ses recherches, qui combinent méthodes ethnographiques et statistiques, portent sur l'élevage, la santé au travail et la surveillance de masse.

**[Nicolas Mariot](http://nicolas.mariot.cnrs.free.fr/)** est historien et sociologue, directeur de recherche au Centre européen de sociologie et de science politique (CNRS, EHESS et université Paris 1-Panthéon Sorbonne). Les notions d'obéissance et de conformisme sont depuis longtemps au coeur de son travail. Il fait partie du comité de pilotage du projet ANR « La vie en confinement » (Vico), dont les données constituent une partie du matériau utilisé dans ce livre. Il est l'auteur de nombreux ouvrages, parmi lesquels : *Intellectuels empêchés. Ou comment penser dans l'épreuve* (dir. avec Brigitte Gaïti, ENS Éditions, 2021), *Histoire d'un sacrifice. Robert, Alice et la guerre* (Seuil, 2017), *Tous unis dans la tranchée ? 1914-1918, les intellectuels rencontrent le peuple* (Seuil, 2013) ou *Face à la persécution. 991 Juifs dans la guerre* (avec Claire Zalc, Odile Jacob, 2010).