---
title: "Bibliographie"
sidebar: false
---

## Effectiveness

La dernière publication de référence sur l'efficacité des confinements date d'août 2023. Il s'agit du rapport de la *Royal Society* intitulé *COVID-19: examining the effectiveness of non-pharmaceutical interventions*.

Dans la synthèse du rapport, on peut lire :

> In general, the studied social distancing measures were associated with considerable reductions in community-level transmission of SARS-CoV-2 and the growth of the epidemic. Measures of greater stringency were typically associated with greater reductions in transmission during the COVID-19 pandemic, demonstrating what epidemiologists call a biological gradient39. Stay-at-home orders, physical distancing measures, and restrictions on gathering sizes were repeatedly found to be associated with substantial community-wide reductions in SARS-CoV-2 transmission and were frequently assessed using the time- varying reproduction number, Rt. [@theroyalsociety2023, p. 32]

Cette assertion s'appuie sur une vaste revue de littérature présentée en détail dans six articles, publiés en même temps que le rapport principal. On trouve un article pour chaque type « d'intervention non-pharmaceutique » : port du masque, tester-tracer-isoler, mesures « environnementales » (aération, désinfection), fermeture des frontières, campagnes de communication et mesures de distanciation sociale (qui incluent aussi bien la fermeture des écoles et des lieux de travail que la limitation des rassemblements l'obligation de rester chez soi).

Dans l'article consacré aux mesures de distanciation sociale, on peut lire :

> During the COVID-19 pandemic, stay-at-home orders were also referred to as lockdowns, shelter- in-place, mandatory control orders or in some locations as circuit-breaking measures. Italy was the first European country to implement stay-at-home orders on 9 March 2020, lasting over 60 days. As infections spread, the UK also announced a lockdown on 23 March 2020 and began a phased reopening by mid-May that year. Here, we included 151 studies estimating the effectiveness of stay-at-home orders (electronic supplementary material, appendix A, Table S13), 119 of which found a substantial benefit resulting in a reduction of the reproduction number (Rt) \[16,23,33,35,38,45,48,60--97\], incidence of SARS-CoV-2 infection \[29,50,52,98--129\] and mortality \[107,116,130--143\].

> Among the studies that reported a relative reduction in Rt, most estimated substantial reductions of around 50%, although there was a wide range of effects (6--81%). These studies had different study designs, populations and definitions for stay-at-home orders. **They were mainly carried out at a national scale within the first year of the pandemic** (electronic supplementary material, appendix C). **Definitions differed in stringency**, where a stay-at-home order may include lockdown-type measures such as restricting internal travel and imposing limitations on gatherings versus the most stringent where individuals were unable to leave their homes for anything other than exercise or essential shopping. A modelling study that estimated the effects of 17 non-pharmaceutical interventions across two waves in seven European countries estimated that a lockdown (banning all gatherings and closing all non-essential businesses) reduced the Rt by 52% (95% CrI: 47%, 56%) \[45\]. Two studies in the US in 2020 found similar reductions, estimating a reduction of Rt by 51% (95% CI: 46%, 57%) after stay-at-home orders were implemented in some states \[38,80\]. However, another study carried out on a multi-national scale in early 2020 concluded that stay-at-home orders **had a relatively small additional effect (on top of business closures, school closures and gathering restrictions that were already in place)**, reducing the Rt by 13% (95% prediction interval (PI): 5%, 31%) \[16\]. A study in Europe in 2020 also estimated **a smaller additional effect of lockdowns when implemented on top of other measures** \[28\].

> Studies that estimated the impact of stay-at-home orders on COVID-19 incidence varied across settings. A study in Australia from 2020 to 2021 estimated that the lockdown in Victoria decreased the incidence of COVID-19 two weeks after its implementation (incidence rate ratio (IRR): 0.88; 95% CI: 0.86, 0.91) \[113\]. In comparison, a multi-national analysis that looked at 210 countries in early 2020 **found that stay-at-home orders reduced the incidence of COVID-19 by 11.2%** \[52\]. Three studies **did not find a significant association between stay-at-home orders and COVID-19 cases** \[14,28,144\]. However, the effectiveness of stay-at-home measures on reducing mortality was mixed, with 16 studies \[107,116,130--141\] reporting reductions, and nine studies reporting no significant associations \[19,28,30,47,144--148\]. Nevertheless, one study in Europe \[28\] and another in the US \[144\] concluded that social distancing behaviours had already changed substantially before stay-at-home orders were implemented in early 2020, and therefore **little additional benefit was observed after the stay-at-home orders were issued.** [@murphy2023, pp. 5-6]

Autrement dit :

Si on lit simplement la synthèse du rapport, on a l'impression qu'il existe un consensus scientifique sur l'efficacité des confinements (*lockdowns*).

Si on lit rapidement la revue de littérature sur laquelle le rapport repose, on ne peut que constater que les scientifiques sont partagés sur la question.

Si on lit *attentivement* cette même revue de littérature, on s'aperçoit que ce désaccord apparent masque un problème terminologique, et qu'il y a en fait deux définitions de *lockdown* et deux consensus scientifiques nullement contradictoires :

1)  Le paquet des mesures de distanciation sociale (incluant l'interdiction des rassemblements, la fermeture des écoles et des lieux de travail, etc.) a été efficace.
2)  L'interdiction de sortir de chez soi sauf « bonne raison » a eu un effet faible (une baisse du Rt de l'ordre de 10%) ou nul.

## Compliance

Dès les premiers temps de l'enquête, nous avons été frappés par le peu d'intérêt apparent des chercheuses et chercheurs pour la dimension policière des mesures prises, en France comme ailleurs dans le monde. Une fois l'enfermement du printemps 2020 derrière nous, la situation n'a guère évolué : dans nombre de pays, et particulièrement là où les confinements furent durs, les tentatives, autant journalistiques qu'universitaires, pour dresser un panorama ou tirer un bilan de l'expérience de mise en cause des libertés sont rares sinon absentes.

Cette situation particulière explique que le livre ne propose pas un état des lieux en bonne et due forme des travaux scientifiques consacrés à tenter d'expliquer "l'adhésion" mondiale aux règles mises en place pour combattre l'expansion du virus.

Bien évidemment, une telle absence de revue de littérature ne signifie pas que celle-ci n'existe pas : elle est même pléthorique. Ainsi nous avons pu dénombrer au moins une soixantaine d'articles, publiés dans des revues scientifiques, qui sont entièrement dédiés à chercher les raisons du respect massif des mesures imposées. Leur format, bien résumé par le titre qui leur est donné : « *Factors Influencing compliance* (parfois *Determinants of adherence*) *with COVID-19 Measures* » , consiste presque toujours en un même exercice : mettre en lumière, à travers une régression, les déterminants « toutes choses égales par ailleurs » de cette obéissance aux règles.

Si certaines études utilisent, comme nous l'avons fait, les données de *Google mobility* comme indicateurs de conformité, l'obéissance est le plus souvent mesurée par les réponses données à un sondage, souvent rémunéré, dans lequel on demande aux gens s'ils ont respecté un certain nombre d'impératifs dans la semaine qui précède l'enquête (ne pas sortir, respecter les distances barrières, ne pas rencontrer des proches habitant en dehors du foyer, etc.). Cette échelle ou indicateur du respect est ensuite rapporté à un ensemble plus ou moins important de variables présumées explicatives, qui vont des variables socio-démographiques classiques (genre, âge, niveau d'études, niveau de salaire, position professionnelle, etc.) aux variables de positionnement et de jugement politique (faites-vous confiance au gouvernement ? Avez-vous foi dans le fonctionnement démocratique du pays ?) en passant par les variables sanitaires (exposition au et peur du virus notamment).

On ne peut ici évoquer l'ensemble de ces enquêtes. Il faudrait pour cela proposer une revue de littérature sur la question semblable à celle menée à propos d'un ensemble de pas moins de 77 articles traitant uniquement des effets supposés de la perception du risque (médical) sur l'adoption de comportements de protection adaptés [@cipolletta2022]. Ou encore à celle consacrée, à partir des résultats de 12 études, aux effets présumés de la « confiance » dans l'acceptation des règles [@devine2021].

Contentons nous d'indiquer qu'elles sont reproduites d'un pays à un autre. On en trouve ainsi (on se limite ici à un article par pays) pour la Suède [@esaiasson2021], l'Autriche [@siebenhofer2022], l'Italie [@guglielmi2020], l'Espagne [@beca-martinez2022], la Suisse [@butty2022], la France [@brouard2020], l'Australie [@murphy2020], l'Équateur [@gonzalez2022], la Grande-Bretagne [@eggers2022 ; @schneider2021], les Pays-Bas [@schraff2021], la Grèce [@anastasiou2021], Israël [@goren2022a], la Thaïlande [@saechang2021], l'Éthiopie [@shanka2022], les États-Unis [@nikolov2020], la Russie [@parfenova2020], la Roumanie [@radu2021] ou la Corée du Sud [@jang2022].

Ou développées dans un cadre comparatif [@clark2020 ; @bargain2020 ; @becher2021 ; @bol2021].

Comment expliquer, alors même que l'objet de ces travaux semble directement lié au nôtre, que nous ne les ayons pas mentionnés, ou de façon incidente, dans le texte ? La raison en est simple : dans la très grande majorité des cas, l'existence du contrôle policier et de la sanction n'est simplement pas intégrée à l'analyse. Les auteurs renvoient l'obéissance de façon quasi exclusive à des dimensions normatives : perceptions et jugements politiques, niveau de confiance et d'optimisme des enquêtés.

Quelques articles cherchent bien à faire la part de la présence policière, du devoir moral et de la confiance politique dans l'explication de l'obéissance. Mais ils ont la particularité (voir le chapitre 4 du livre) d'être consacrés aux cas de l'Australie [@murphy2020], des États-Unis [@vanrooij2020] ou de la Grande Bretagne [@kooistra2020], soit des pays à confinement « lâche » à propos lesquels on pouvait faire l'hypothèse que surveillance et sanction ne joueraient qu'un faible rôle dans le respect des obligations.

Paradoxalement, s'il existe de nombreuses enquêtes sur le modèle « *Determinants of compliance with covid-19 measures* » réalisées en Italie [@ladini2022 ; @pedrazzani2021 ; @guglielmi2020], en France[@brouard2020 ; @anderson2022a ; @raude2020], ou en Espagne [@cabrera-alvarez2022 ; @galende2022 ; @beca-martinez2022 ; @gualda2021 ; @amat2020], aucune, à notre connaissance, ne fait référence à la pression policière et aux amendes.

Arrêtons-nous un instant, pour illustrer ce paradoxe, sur deux études portant sur le cas français. La mise à l'écart des aspects coercitifs des politiques de gestion de la crise y prend deux faces. La première, directe, consiste simplement à évoquer cette dimension répressive « en passant », en la considérant comme quelque chose de périphérique ou de secondaire. Dans leur article sur « l'évolution des perceptions des normes de distanciation sociale » en France durant le confinement [@casoria2021], Fortuna Casoria, Fabio Galeotti et Marie-Claire Villeval mentionnent bien l'existence d'une sanction et le nombre de contrôles et d'amendes distribuées (en note 3 p. 55). Mais c'est pour aussitôt écarter ces éléments : « La menace n'était probablement pas suffisante pour dissuader les violations des mesures de distanciation sociale, car il était pratiquement impossible de surveiller tout le monde en permanence » (p. 55).

En note toujours, les auteurs expliquent encore que « nous n'avons pas mesuré dans quelle mesure les lois sur la distanciation sociale étaient perçues comme dissuasives par les gens. Par conséquent, nous ne pouvons pas exclure que les mesures de distanciation aient également eu un effet dissuasif standard en augmentant le coût monétaire marginal des réunions sociales » (note 4 p. 55). En résumé, ils évacuent toute idée de contrainte : ils observent que les interventions d'Emmanuel Macron le 13 mars n'ont guère eu d'effet, au contraire de la mise en place du confinement : comment s'en étonner, sauf si on n'intègre pas le fait que celle-ci s'accompagne d'interdits et de sanctions ?

Le traitement est identique dans l'article de Christopher Anderson : l'auteur mentionne bien les patrouilles de police, l'existence de l'attestation, ou les « restrictions sévères » des libertés alors imposées (« les règles, écrit-il p. 3, étaient soutenues par l'exercice visible du pouvoir coercitif de l'État »), mais lui non plus n'intègre pas ces éléments punitifs à son modèle explicatif. Alors même qu'il explique vouloir trouver la source de l'obéissance dans la rencontre entre « ce que l'État fait et ce que les gens croient [@anderson2022a, p. 4] », la première partie de la proposition est essentiellement réduite à l'effort de persuasion développé par les autorités, et particulièrement, dans l'article, aux effets supposés puissants du discours présidentiel du 16 mars.

A cet égard pourtant, la conclusion de l'article est décevante : l'auteur reconnaît en effet ne pas savoir si l'efficacité apparente de la parole du chef de l'État, mesurée par les différences de pratiques entre des personnes ayant répondu à un sondage le 16 mars avant le discours et le 17 mars, tient plutôt à la nature du discours, à son contenu, à un simple « sens du devoir » chez les citoyens, à un traditionnel soutien au gouvernement dans les crises ou encore ... « aux sanctions en cas de violation des règles [@anderson2022a, p. 18] ». Concernant ce dernier élément, la tâche semble en effet impossible dès lors que l'article dépeint un paysage de confinement d'où patrouilles, drones, contrôles et amendes ont disparu ou n'apparaissent qu'en filigrane, sous la forme d'un arrière-plan sans conséquences concrètes.

L'autre face de cette mise à l'écart de la coercition est plus subtile et plus indirecte. Elle consiste en un choix de vocabulaire qui évite de parler d'interdits ou même de règles pour préférer évoquer de simples changements de comportements ou d'habitudes, tout juste influencés par les recommandations ou incitations gouvernementales. Pour le dire simplement, le regard est entièrement tourné vers les confinés, très peu vers les confineurs, comme si l'explication de l'obéissance devait être entièrement cherchée du côté de la décision des premiers de se plier aux injonctions des seconds. L'article de Fortuna Casoria, Fabio Galeotti et Marie-Claire Villeval s'intéresse ainsi à l'évolution brutale de « la perception des normes sociales, comme le fait de rencontrer des amis, d'organiser des évènements sociaux ou de serrer la main ». Comme si tout cela ne relevait que d'une adaptation personnelle. Les auteurs disent ainsi tenter de comprendre la conjonction entre perceptions normatives et adaptations comportementales. Ils montrent, sans surprise, que durant le confinement les enquêtés jugent inappropriée aux circonstances une proposition comme « La semaine dernière, M. X a invité des amis à dîner » (norme, fig. 1 p. 59), et qu'eux-mêmes déclarent ne pas avoir invité des membres de la famille ou des amis dans la semaine qui précède (comportement congruent avec la norme, fig. 2 p. 61). La nouvelle norme est acceptée, le comportement attendu adopté. Dans ce mouvement, nulle place pour l'interdiction légale ou la police.

De son côté, Christopher Anderson décrit le confinement comme un échange entre les impulsions gouvernementales et les « réponses citoyennes » qui, pour prendre place dans une situation de crise, n'en respecte pas moins les formes ordinaires du jeu démocratique. « Les courbes de la Figure 4 prouvent que les efforts de persuasion du gouvernement français, ainsi que le confinement proprement dit, ont contribué à faire comprendre aux gens la nécessité de se conformer » écrit-il ainsi. Le gouvernement a « signalé » aux Français des « comportements désirables » : ceux-ci ont répondu positivement à ces espoirs[@anderson2022a, p. 12]. Pour rendre plausible une telle description, l'auteur assimile les interdits du confinement, notamment les restrictions de déplacement, à de simples adaptations de comportement semblables aux incitations à manger sain ou à mieux recycler les déchets [@anderson2022a, p. 17] -- sans même préciser que, dans ce dernier cas, la recommandation s'accompagne d'incitations financières directes et ne dépend donc pas entièrement du bon vouloir du consommateur. Dans ce cadre, il pose une équivalence entre des recommandations individuelles, comme le fait de se laver les mains, et des interdictions légales comme celles qui concernent les sorties : « Après tout, les comportements que les gouvernements ont cherché à façonner sont des décisions habituelles liées à des choses comme l'hygiène personnelle (par exemple, se laver les mains, éternuer), les rituels d'interactions sociales (par exemple, saluer les autres) ou le mouvement (par exemple, le mode de déplacement, prendre de la distance lors d'une promenade)[@anderson2022a, p. 17] ». La description est évidemment inexacte : si le fait de se laver les mains n'est pas contrôlable, il en va tout autrement de l'interdiction de sortie, ou de sa stricte limitation, qui ne relève en rien, puisqu'elle est punissable, d'un simple changement volontaire d'habitude. Ce que le confinement a de spécifique tient précisément au fait que la plupart des libertés publiques ont été suspendues, et donc que les liens entre gouvernants et gouvernés ne peuvent plus relever simplement du dialogue ou de l'échange, comme si tout un chacun pouvait librement décider de se plier ou non aux restrictions.

Concluons donc provisoirement : si l'on se tourne du côté des (nombreux) travaux dont l'objectif consiste, de façon exclusive, à déterminer les raisons de la conformité aux règles, alors il faut constater qu'aux quelques exceptions près mentionnées, ils ne nous aident guère parce qu'ils considèrent que l'obéissance ne doit rien aux politiques de surveillance et de répression mises en œuvre, mais tout ou presque à la volonté personnelle, à l'état psychologique ou aux valeurs politiques des confinés. Il est toutefois possible que cette insistance à lier la conformité au soutien au gouvernement ou à la confiance dans les autorités, dans les institutions démocratiques locales ou simplement dans l'avenir, tienne aux routines de ce type d'enquêtes qui, pour d'autres problèmes que ceux liés à la crise sanitaire, avaient régulièrement recours aux indicateurs standardisés transnationaux renvoyant aux enjeux d'une « confiance » (*trust*) multiforme.

Qu'en est-il alors des enquêtes plus vastes expressément développées pour étudier la crise sanitaire dans les pays qui nous intéressent, ceux où le confinement a été l'objet de mesures d'ordre public spécifiques ? Ont-elles, à la différence de celles dont il vient d'être question, intégré à leur dispositif des instruments pour mesurer le rôle joué localement par les attestations, les contrôles et les verbalisations ?

De ce côté-ci également, c'est le silence qui domine, quand bien même il existe des enquêtes ad hoc exclusivement consacrées à étudier les différents aspects de la crise sanitaire. En Espagne, l'ouvrage collectif *COVID-19 and Social Change in Spain*, pourtant élaboré à partir d'un blog collectif tenu dans le temps même du confinement (« sociologie en quarantaine » : <https://sociologiaencuarentena.tumblr.com/>), ne propose aucune analyse systématique de la pression policière et des amendes distribuées, alors même que le pays, on l'a vu, possède en la matière le record d'Europe [@castro2022]. Il en est de même de l'enquête italienne *ResPOnsE COVID-19* (Risposta dell'Opinione Pubblica Italiana all'Emergenza Covid-19), proche de Vico par son *design* général et sa politique de mise à disposition des données : très intéressante du point de vue de son contenu, disponible en ligne, rassemblant plus de 30 000 répondants en quatre vagues de passation (dont 15 000 lors de la première, du 6 avril au 6 juillet 2020), son questionnaire ne fait malheureusement aucune référence ni à l'attestation italienne, ni à la surveillance policière et ses conséquences\[\^atelier-5\]. Et d'après les contacts pris auprès de quelques collègues italiens, il n'existe en la matière aucun bilan général, ni dans la presse, ni dans la littérature spécialisée. A dire vrai, le phénomène n'est pas très surprenant : même les tentatives les plus critiques de synthèse des politiques de gestion de la crise, comme celle proposée par l'historien africaniste Toby Green dans un essai stimulant, ne s'intéressent que très marginalement à la police du confinement [@green2021].

En France, l'enfermement du printemps 2020 a bien entendu également donné lieu à une production scientifique considérable, y compris en sciences sociales. Pour s'en donner une idée, on peut renvoyer ici, parmi d'autres, à la [bibliographie](https://www.irdes.fr/documentation/syntheses/covid-19-elements-de-litterature-scientifique-2e-partie.pdf) établie en mars 2021 par le centre de documentation de l'Institut de Recherche et Documentation en Économie de la Santé.

La quasi totalité de ces travaux l'envisage comme une catastrophe naturelle dont on scrute les conséquences -- sur les inégalités, la santé mentale, le recours au soin, les relations familiales et amicales, les apprentissages scolaires, les réorientations professionnelles, la politisation --, mais on chercherait en vain ceux qui tentent de comprendre pourquoi les gens s'y sont conformés.

Les principales enquêtes sociologiques publiées [@lambert2021 ; @peretti-watel2022a] ne s'intéressent pas à la question. Hormis les travaux, déjà mentionnés plus haut, menés par ou avec Sebastian Roché [@roche2020 ; @roche2020a ; @terpstra2021], ou ceux initiés par les juristes [@slama2021 ; @boulestreau2020], personne n'a porté d'attention soutenue à l'importance et à l'ampleur de la police du confinement.

Se tourner vers les médias ou les institutions politiques ne permet guère de progresser. A notre connaissance, aucun organe de presse généraliste n'a proposé de bilan général des politiques publiques de confinement, notamment pour ce qui concerne leur dimension policière. Il est toutefois possible que la situation évolue sur ce point. Au moment où nous apportons les dernières modifications au livre, l'agence Reuters vient de mettre en ligne deux articles consacrés à commenter l'évolution du nombre d'Amendes forfaitaires délictuelles (AFD) depuis 2018, hors contrôles routiers (là encore, ses journalistes ont obtenu ces données à la suite d'un recours devant la CADA) : on est passé de 240 000 verbalisations en 2018 à 1,5 millions en 2021, avec un pic à plus de 2 millions en 2020 [@foroudi2022]. Sans doute le confinement a-t-il été, en la matière, l'occasion d'un effet de cliquet.

Dans le même sens, aucun des deux rapports parlementaires consacrés à la « gestion » et aux conséquences « dans toutes ses dimensions » de la crise sanitaire ne fait mention de l'attestation dérogatoire de sortie [@ferrand2020 ; @borowczyk2020]. Le premier consacre moins de deux pages (16-17) à « l'impact de l'état d'urgence sur les libertés publiques », mentionnant, sans autre commentaire, le nombre de contrôles et verbalisations fin avril, avant de conclure que « ces restrictions, qui ont eu un impact important et immédiat sur la vie quotidienne des Français, n'en ont pas moins été strictement encadrées par le législateur ». Les récits publiés par certains des principaux acteurs de la crise ne s'étendent guère plus. Comme on l'a vu, celui d'Olivier Véran, alors ministre de la Santé, consacre à peine une page à justifier comme évidente la mise en place de l'attestation. Deux ans après les faits, il énonce ce que personne n'avait alors explicitement affirmé : que l'attestation était un outil de police [@veran2022]. Aurélien Rousseau, alors responsable de l'Agence Régionale de Santé d'Île de France, devenu directeur de cabinet de la Première Ministre à Matignon au moment où nous terminons ce livre, ne mentionne quant à lui ni l'attestation ni les amendes au long des 170 pages qu'il consacre à la crise [@rousseau2022].

Inutile de poursuivre plus loin cette quête manifestement vaine : de quelques côtés que l'on se tourne, peu de gens ont eu envie de revenir de manière un tant soit peu approfondie sur l'expérience d'obéissance de masse du printemps 2020. En un sens, ce silence a représenté un moteur pour notre propre travail.

## Surveillance

La revue \_Surveillance & Society\_ a publié en 2021 un [numéro spécial](https://ojs.library.queensu.ca/index.php/surveillance-and-society/issue/view/890) sur les liens entre pandémie de COVID-19 et surveillance de masse. On y trouve notamment un article sur le fonctionnement du "code santé" en Chine [@cassiano2021].
