---
title: "Films"
---

## FAQ

Un tour du monde de cette sorte rencontre inévitablement les images de drones qui constituent la principale archive visuelle de l'évènement... (p. 18)

{{< video https://www.youtube.com/watch?v=x_xoTU_c_DI >}}

## L'art français du confinement

Dans la soirée, le ministre de l'Intérieur complète les annonces présidentielles... (p. 86)

{{< video https://www.youtube.com/watch?v=AGifYXBlDQ0 start="210" >}}

## La police des sorties

Certes, nombre d'unités de police et de gendarmerie ont généreusement partagé leur quotidien sur les réseaux sociaux... (p. 134)

{{< video https://www.youtube.com/watch?v=M0yTTUt_zGA >}}

## Inquiètement

Ces animaux filmés au cœur des villes sont d'ailleurs une constante internationale, depuis 
le puma aperçu à Santiago au Chili jusqu'au troupeau de chèvres sauvages qui occupe la station balnéaire de Llandudno au pays de Galles... (p. 188)

{{< video https://www.youtube.com/watch?v=xcDvM3PdVsc >}}

Sur la promenade des Anglais complètement désertée, roulent deux policiers à moto... (p. 207)

{{< video https://www.youtube.com/watch?v=9dcxl4zk5fs&t=5s >}}

## Lignes de conduite

Maxime Matthys, un jeune artiste belge installé à Rennes, a fait le 23 mars une performance dénommée "Sortez couverts"... (p. 268)

{{< video https://youtu.be/dHzazF-LD-w?si=C6nPIGX3JK-Ge_10 >}}

## Les attraits de l'enfermement

À Neufchâteau dans les Vosges, le 21 mars, un reportage de France 3 montre les gendarmes en pleine leçon des choses du confinement... (p. 296)

{{< video https://www.youtube.com/watch?v=Hi5ZIDNTSnQ >}}
