---
title: "Mode d'emploi"
sidebar: false
---

::: {.callout-note}
## Quelques précédents

Cet "atelier" de la recherche répète l'opération de méthode déjà effectuée dans le cadre de précédentes enquêtes. Voir "Retour sur enquête" dans @mariot2010, p. 241-260, la postface "Échafaudages" dans @mariot2013, p. 387-437 ou encore "Les dessous du récit" dans @mariot2017, p. 367-388.
:::

## Un prestigieux contre-exemple

> I’m conscious that lots of people would like to see and run the pandemic simulation code we are using to model control measures against COVID-19. To explain the background - I wrote the code (thousands of lines of undocumented C) 13+ years ago to model flu pandemics [@ferguson2020a ; cité dans @pouzat2022]…

Le 16 mars 2020, l'épidémiologiste Neil Ferguson et son équipe de l'*Imperial College* de Londres, publiaient – dans l'urgence – un rapport annonçant qu'en l'absence de mesures de confinement, le virus pourrait causer 510 000 morts au Royaume-Uni et 2.2 millions aux États-Unis [@ferguson2020]. Ce rapport a circulé bien au-delà du petit monde des spécialistes en santé publique, car on lui attribue notamment le revirement de Boris Johnson et la décision de confiner la Grande-Bretagne. L'étude s'appuyait, comme son principal auteur l'a reconnu, sur des milliers de lignes de code *C* non documentées, écrites dans les années 2000 pour modéliser des épidémies de grippe. Ces algorithmes n'ont été publiés qu'un an plus tard, en avril 2021, après avoir été réécrits [@pouzat2022]. 