---
title: "Sources françaises"
---

## Enquête VICO

Il nous faut débuter l'inventaire en évoquant l'étude « La Vie en confinement ». C'est en effet par elle que ce travail a commencé, au cœur même de l'épisode, lorsque fut lancée en ligne, entre le 15 avril et le 11 mai 2020, cette enquête par questionnaire[^atelier-1]. Interpellés par le caractère trans-classes des mesures prises, surpris par la mise en place de l'attestation, nous étions résolus à lancer une investigation dans le temps même de l'événement -- au jour le jour et non après coup, lorsqu'on a le recul du temps, il est important de le souligner. Faute de trouver un panel de sondage existant qui aurait accepté d'inclure quelques questions portant sur l'obéissance et la triche dans les usages de la fiche gouvernementale, nous avons fait le choix, avec quelques collègues, d'établir dans l'urgence un questionnaire qu'on diffuserait par nos propres moyens. Bien nous en a pris : grâce à l'aide précieuse d'un réseau d'enseignants des facultés de sociologie qui ont relayé l'enquête auprès des étudiants et de leurs familles, mais aussi et surtout des rédactions de quotidiens de presse régionale qui ont accepté de mettre notre questionnaire en ligne sur leurs sites internet, plus de 15 000 personnes y ont répondu de manière complète et exploitable. Ce sont ces réponses qui nous permettent d'identifier les réactions individuelles aux règles mises en place.

## Remarques libres

Mais VICO a un atout supplémentaire, celui d'ajouter à ces réponses quantifiables aux questions soulevées par l'enquêteur, des développements beaucoup moins contraints puisque laissés à l'initiative des répondants. Ceux-ci avaient en effet l'opportunité, dans un dernier effort au terme du questionnaire, de proposer un commentaire de leur choix dans une case dévolue à cet objectif. Or parmi les 15 000 répondants, pas moins de 3000 ont accepté de dire leur sentiment sur l'étrange expérience qu'ils étaient en train de vivre, souvent en quelques lignes, parfois plus longuement[^atelier-2]. Les thèmes abordés sont on ne peut plus variés. Certains parlent de la difficulté d'occuper leurs enfants, de leurs problèmes de sommeil, du bruit des voisins, des avantages ou des inconvénients du télétravail. D'autres évoquent leurs loisirs, la manière dont ils occupent leurs journées, les privilèges dont le confinement leur fait prendre conscience : avoir une maison, un jardin, un chien. Beaucoup confient leur ennui, leur solitude lancinante, le temps qui s'étire et perd son sens, les jours qui se ressemblent, les chantiers annulés, les aides publiques auxquelles ils n'ont pas droit. Il y aussi les commentaires pleins de colère sur la gestion de la crise par le gouvernement et de sa couverture par les médias, l'angoisse de se faire contrôler par la police, l'exaspération que suscite l'attestation de sortie. Sans compter, enfin, tous les gens qui dénoncent les infractions au confinement des voisins, demandent des précisions sur les règles de sortie ou regrettent de ne pas être « dans les cases » du questionnaire. Rassemblées, ces remarques composent un recueil de quelques 500 pages : elles constituent un matériau d'une rare richesse que nous avons mobilisé tout au long du livre.

## Campagne d'entretiens

La force de cette source tient à ce que les gens ont évoqué ce qui leur tenait vraiment à cœur. S'ils tiennent à donner leur sentiment sur les contrôles de police ou l'attestation de sortie alors qu'ils ont déjà passé une heure (problèmes de connexion compris) à remplir le questionnaire, c'est qu'il s'agit d'un aspect important pour eux. La limite est qu'on ne pouvait pas demander de développer. Quand une jeune femme écrit, par exemple, cette seule phrase, « j'ai peur de sortir », on aimerait en savoir plus. On a donc organisé une campagne d'entretiens, dans le cadre d'un atelier de master, durant l'hiver 2020-2021. Chaque étudiant devait réaliser cinq entretiens auprès de « proches de proches », en les choisissant dans l'objectif de maximiser les différences (d'âge, de genre, de lieu de vie et de milieu social) entre les différents enquêtés. Les questions portaient spécifiquement sur le rapport aux règles de sortie, les usages de l'attestation et les contrôles de police.

## Chasse aux chiffres

Ces différentes sources sont mobilisées tout au long de la seconde partie du livre, celle qui s'intéresse aux logiques de la conformation. Mais, pour enquêter sur l'activité policière, nous avions besoin d'autres données, et notamment des chiffres territorialisés des verbalisations et des contrôles. En la matière la situation est contrastée. Pour ce qui concerne les amendes, les données par département sont systématiques puisque nous disposons des chiffres enregistrés par l'Agence Nationale de Traitement Automatisé des Infractions (ANTAI), et tardivement rendus publics grâce à l'opiniâtreté d'un journaliste indépendant[@lechenet2021].

En revanche, nous ne disposons pas d'une distribution départementale équivalente pour ce qui concerne les totalisations des contrôles, les services du Ministère de l'Intérieur ne les ayant jamais rendues publiques. Or ces données des contrôles sont a priori les plus importantes au sens où, comme on l'a vu, c'est l'universalité potentielle des vérifications, plus que l'importance des amendes, qui constitue la véritable « nouveauté » induite par le confinement en matière d'ordre public. Pour résorber ce manque, nous avons déployé d'importants efforts pour rassembler les chiffres livrés dans la presse ou sur les réseaux sociaux, au printemps 2020, par les préfectures et les mairies qui avaient alors fait le choix de « communiquer ». Grâce à ce travail, nous disposons, au terme de la récolte, d'une solide base de données rassemblant les chiffres des vérifications rendus publics pour la gendarmerie, la police nationale et la police municipale, ensemble ou séparément, à différentes dates et pour 22 villes et 60 départements de métropole. Ces chiffres montrent d'impressionnantes différences de traitement selon les territoires. Certaines sont relativement attendues. Il aurait été pour le moins bizarre de s'acharner à verbaliser les habitants de la Lozère, par exemple. D'autres posent davantage de questions.

## Entretiens de Marion Guénot

L'étude de l'activité des forces de l'ordre a également bénéficié de l'apport d'une enquête menée à l'automne 2020 par une chercheuse au Centre de Recherches sur le Droit et les Institutions Pénales, Marion Guénot, que nous remercions chaleureusement pour son aide précieuse. L'étude visait à comprendre en quoi le confinement avait transformé les pratiques quotidiennes des forces de l'ordre. En acceptant avec gentillesse de mettre ses données (non encore publiées) à notre disposition (entretiens et résultats d'un questionnaire diffusé en interne), notre collègue nous a permis de retourner le miroir de notre propre enquête en accédant au regard portés par les policiers eux-mêmes sur les tâches de surveillance de la présence humaine dans l'espace public qui constituaient alors l'essentiel de leur activité.

## Histoires de confinement

Le versant « national » de l'enquête repose enfin sur un matériau extrêmement riche et assez inhabituel, constitué de plus de 250 « histoires du confinement » tirées de la presse locale et de la communication des forces de l'ordre. Souvent, la frontière entre ces deux sources est assez ténue. Pour qu'il n'y ait pas de méprise, signalons d'emblée qu'aucune de ces histoires ne se déroule entre quatre murs. Toutes se passent dans l'étrange dehors du printemps 2020, dans les rues, sur les routes, et plus souvent encore dans les forêts, les parcs, sur les plages, parfois dans des grottes ou des refuges de haute montagne. Elles racontent le quadrillage du terrain par les forces de l'ordre, les verbalisations contestables, ou encore la « traque » des contrevenants, selon le mot fréquemment employé aussi bien par les policiers et gendarmes que par les reporters locaux. Elles font émerger la minorité nécessairement discrète des « réfractaires au confinement », celles et ceux qui ont continué à fréquenter les zones interdites malgré la présence policière. Après de premiers coups de sonde fructueux, l'investigation a pris un tour systématique, ce qu'internet rend désormais possible : armés de quelques mots clés (« confinement », « contrôles », mais aussi « barbecue » ou « drones »), nous avons interrogé un moteur de recherche pour chaque département métropolitain, et pour la période allant du 16 mars au 30 mai 2020. Ces histoires, qui pour la plupart ne dépassent pas 500 mots, ont tout de petites fables de circonstance, mettant en scène les dangers que présentent les transgressions du confinement.

Elles renseignent sur au moins trois choses qui nous intéressent au premier chef. Ce sont d'abord les moyens mis en œuvre pour la surveillance de la population. Grâce à elles, nous avons pu documenter l'usage systématique des drones, des hélicoptères et des caméras de surveillance. Ensuite, elles montrent qu'un certain nombre de personnes ont continué à braver les interdits tout au long du confinement. Enfin, elles documentent la politique de communication des autorités et ses relais médiatiques. C'est naturellement le cas lorsque les policiers et gendarmes font leur propre publicité, ou lorsque tel maire vante l'action de sa police municipale. Souvent, il s'agit d'informer en même temps que d'inquiéter en répétant la leçon, comme dans les Pyrénées-Orientales où la gendarmerie publie sur sa page *Facebook*, le 24 mars, une carte de son quadrillage du territoire -- les points de contrôle fixes -- accompagnée du commentaire suivant : « Le groupement de gendarmerie départementale des Pyrénées-Orientales est plus que jamais mobilisé, PARTOUT et TOUT LE TEMPS, pour vous protéger, pour assurer l'intégrité des biens et pour vérifier que vous RESTEZ CHEZ VOUS [@t.2020] ». Parfois, les forces de l'ordre préfèrent simplement mettre en scène leur quotidien, comme dans la série « Bleu » dont les gendarmes de Dordogne diffusent le premier épisode le 4 avril sur leur chaîne Youtube[@g.2020b]. Ailleurs encore, elles commentent leurs succès sur les réseaux sociaux, voire profitent des drones et hélicoptères utilisés au quotidien pour filmer les beautés de la France (vide) vue du ciel -- voir par exemple le film réalisé par la Préfecture de Police pour Paris[@bxr.2020]. Très souvent, elles ont pu alors s'appuyer sur la presse locale pour relayer leur message, tout particulièrement dans le cadre d'innombrables publireportages dans lesquels le journaliste « *embeded* » les montrait au travail, sur terre ou dans les airs, en train de surveiller et de contrôler celles et ceux qui s'aventuraient encore dans l'espace public. L'article publié dans le *Berry Républicain* le 2 avril est en ce sens exemplaire. Le localier est invité à assister au premier déploiement de drone dans le ciel de la Préfecture du Cher, en présence de la directrice départementale de la sécurité publique. Sous l'ensemble des images et de la vidéo qui illustrent l'article, le « crédit photographique » indique : « SRPJ Orléans »[@letreulle2020].

Comme on a pu le constater dans les pages qui précèdent, nombre de quotidiens ou d'hebdomadaires, qu'ils soient nationaux ou régionaux, ne se sont guère écartés de cette ligne de promotion du travail de l'État. A de rares exceptions près (celles d'organes qu'on qualifie, souvent avec une connotation péjorative, de « militants » : *Reporterre*, *Bastamag*, *Rue89*[@gerardin2020] ou le service « CheckNews » de *Libération* par exemple), ils se sont en quelque sorte auto-institués, à l'instar de très nombreuses municipalités, comme relais et bras droit des autorités pour diffuser et rappeler les mesures prises dans le cadre de l'état d'urgence. Une des manifestations les plus frappantes de la couverture médiatique des événements du printemps 2020 tient ainsi à la récurrence de ces reportages réalisés aux côtés des forces de l'ordre.

Ce caractère particulier des sources n'est pas sans intérêt pour qui souhaite comprendre les ressorts du conformisme. De façon quasi unanime, les journaux ont servi de caisse de résonance aux « points presse » officiels, n'interrogeant que très rarement les choix et dispositifs mis en place. D'aucun mentionneront ici, en contrepoint, les quelques articles critiquant l'enlèvement des bancs publics à Béziers ou l'appel aux chasseurs du préfet de Seine et Marne. Mais outre que ces exemples restaient justement présentés comme des cas hors norme, déviants (là ils exagèrent), ils laissent dans l'ombre toutes les fois où des propos étonnants tenus par des préfets, des directeurs de la sécurité publique ou des maires -- on en a lu de nombreux exemples -- ont été relayés tels quels, sans commentaires. En se rangeant parmi les acteurs de la lutte contre la pandémie, les organes de presse n'ont pas peu contribué à rendre invisible sinon indicible toute parole qui viendrait discuter les choix officiels. Ce faisant, ils ont, eux aussi, pris une part non négligeable dans la fabrique du conformisme.