---
title: "Tables"
toc-depth: 2
---


## Table des matières

### Introduction

- La police pour tous
- Une société aux aguets
- L’obéissance « grandeur nature »

### FAQ

- Mode d’emploi
- Tous les confinements sont-ils des clones de Wuhan ? 
- Qu’est-ce qu’un confinement ?
- Les gouvernements avaient-ils de bonnes intentions ? 
- Aurait-on pu se passer d’un confinement ? 
- Quel a été le confinement le plus dur d’Europe ? 
- Où passer le prochain ?

### L’art français du confinement

- Emprunts et bricolages
- Vérité
- Un nouveau concours Lépine
- Le soupçon généralisé d’infraction

### La police des sorties

- Choc moral
- Quadriller et punir
- Double peine
- Retour de bâton
- Discrétion
- Règlements de compte
- Bilan des exercices

### Inquiètement

- Les yeux de l’État
- La menace
- La peur du dehors
- Hors la loi

### Lignes de conduite

- Aux antipodes
- Six espèces de confinés
- Les formes de l'opposition
- Les logiques de l'obéissance

### Les attraits de l’enfermement

- Le métier de contrôlable
- Aménagements et consentement
- « Renforcez les contrôles ! »

### L’enfermement des femmes

- La police au foyer
- Le vide et ses démons
-Interpellations

### Conclusion

### Index des lieux

### Bibliographie

### Remerciements

### Biographie des auteurs

## Table des graphiques, tableaux, documents et cartes

- Plus les États européens respectaient le droit à l’intégrité physique, moins ils ont enfermé leur population (graphique)
- Plus les États européens comptaient de policiers par habitant, plus ils ont enfermé leur population (graphique)
- Les États européens les plus hostiles aux promenades sont les plus pourvus en policiers (graphique)
- Ampleur des restrictions dans les États européens entre le 1er mars et
le 1er juin 2020 (graphique)
- Une minorité d’États européens ont mis en place des mesures de
surveillance draconiennes (graphique)
- Parc Kralingse Bos, Rotterdam (Pays-Bas), le 23 avril 2020 (document)
- Européens à l'air libre au nord, enfermés au sud et à l'est (graphique)
- La signature des confinements latins (graphique)
- Ampleur et prévalence de la verbalisation dans quelques pays européens (printemps 2020) (tableau)
- Où passer le prochain ? (graphique)
- Premier modèle d'attestation française, 16 mars 2020 (document)
- Deuxième modèle d'attestation française, 23 mars 2020 (document)
- Couvre-feux municipaux au 25 mars 2020 (carte)
- L'inégale distribution des amendes (carte)
- Quadriller et punir (graphique)
- Les variations de sévérité ne sont pas imputables aux différences d'enfermement (graphique)
- Concentrations policières sur la façade méditerranéenne et en Île-de-France (carte)
- Expliquer les variations départementales de la verbalisation au printemps 2020 (tableau)
- Une partie des caméras de surveillance actives à Paris au printemps 2020 (carte)
- Classification des confinés (graphique)
- Les lignes de conduite en fonction des pratiques de confinement (tableau)
- Comparaison des pratiques sociales et émotions des exemplaires et des légalistes (tableau)
- Mots associés à « Dehors », « Sortir » et « Sortie » (graphique)
