---
title: "Enquête La Vie en confinement"
---

Il nous faut débuter l'inventaire en évoquant l'étude « La Vie en confinement ». C'est en effet par elle que ce travail a commencé, au cœur même de l'épisode, lorsque fut lancée en ligne, entre le 15 avril et le 11 mai 2020, cette enquête par questionnaire[^atelier-1]. Interpellés par le caractère trans-classes des mesures prises, surpris par la mise en place de l'attestation, nous étions résolus à lancer une investigation dans le temps même de l'événement -- au jour le jour et non après coup, lorsqu'on a le recul du temps, il est important de le souligner. Faute de trouver un panel de sondage existant qui aurait accepté d'inclure quelques questions portant sur l'obéissance et la triche dans les usages de la fiche gouvernementale, nous avons fait le choix, avec quelques collègues, d'établir dans l'urgence un questionnaire qu'on diffuserait par nos propres moyens. Bien nous en a pris : grâce à l'aide précieuse d'un réseau d'enseignants des facultés de sociologie qui ont relayé l'enquête auprès des étudiants et de leurs familles, mais aussi et surtout des rédactions de quotidiens de presse régionale qui ont accepté de mettre notre questionnaire en ligne sur leurs sites internet, plus de 15 000 personnes y ont répondu de manière complète et exploitable. Ce sont ces réponses qui nous permettent d'identifier les réactions individuelles aux règles mises en place.

Mais VICO a un atout supplémentaire, celui d'ajouter à ces réponses quantifiables aux questions soulevées par l'enquêteur, des développements beaucoup moins contraints puisque laissés à l'initiative des répondants. Ceux-ci avaient en effet l'opportunité, dans un dernier effort au terme du questionnaire, de proposer un commentaire de leur choix dans une case dévolue à cet objectif. Or parmi les 15 000 répondants, pas moins de 3000 ont accepté de dire leur sentiment sur l'étrange expérience qu'ils étaient en train de vivre, souvent en quelques lignes, parfois plus longuement[^atelier-2]. Les thèmes abordés sont on ne peut plus variés. Certains parlent de la difficulté d'occuper leurs enfants, de leurs problèmes de sommeil, du bruit des voisins, des avantages ou des inconvénients du télétravail. D'autres évoquent leurs loisirs, la manière dont ils occupent leurs journées, les privilèges dont le confinement leur fait prendre conscience : avoir une maison, un jardin, un chien. Beaucoup confient leur ennui, leur solitude lancinante, le temps qui s'étire et perd son sens, les jours qui se ressemblent, les chantiers annulés, les aides publiques auxquelles ils n'ont pas droit. Il y aussi les commentaires pleins de colère sur la gestion de la crise par le gouvernement et de sa couverture par les médias, l'angoisse de se faire contrôler par la police, l'exaspération que suscite l'attestation de sortie. Sans compter, enfin, tous les gens qui dénoncent les infractions au confinement des voisins, demandent des précisions sur les règles de sortie ou regrettent de ne pas être « dans les cases » du questionnaire. Rassemblées, ces remarques composent un recueil de quelques 500 pages : elles constituent un matériau d'une rare richesse que nous avons mobilisé tout au long du livre.

La force de cette source tient à ce que les gens ont évoqué ce qui leur tenait vraiment à cœur. S'ils tiennent à donner leur sentiment sur les contrôles de police ou l'attestation de sortie alors qu'ils ont déjà passé une heure (problèmes de connexion compris) à remplir le questionnaire, c'est qu'il s'agit d'un aspect important pour eux. La limite est qu'on ne pouvait pas demander de développer. Quand une jeune femme écrit, par exemple, cette seule phrase, « j'ai peur de sortir », on aimerait en savoir plus. On a donc organisé une campagne d'entretiens, dans le cadre d'un atelier de master, durant l'hiver 2020-2021. Chaque étudiant devait réaliser cinq entretiens auprès de « proches de proches », en les choisissant dans l'objectif de maximiser les différences (d'âge, de genre, de lieu de vie et de milieu social) entre les différents enquêtés. Les questions portaient spécifiquement sur le rapport aux règles de sortie, les usages de l'attestation et les contrôles de police.

[^atelier-1]: Pour une présentation de VICO, voir @mariot2021 et le carnet de recherche lié : <https://vico.hypotheses.org/>