---
title: Histoires de confinement
---

Le versant « national » de l'enquête repose enfin sur un matériau extrêmement riche et assez inhabituel, constitué de plus de 250 « histoires du confinement » tirées de la presse locale et de la communication des forces de l'ordre. Souvent, la frontière entre ces deux sources est assez ténue. Pour qu'il n'y ait pas de méprise, signalons d'emblée qu'aucune de ces histoires ne se déroule entre quatre murs. Toutes se passent dans l'étrange dehors du printemps 2020, dans les rues, sur les routes, et plus souvent encore dans les forêts, les parcs, sur les plages, parfois dans des grottes ou des refuges de haute montagne. Elles racontent le quadrillage du terrain par les forces de l'ordre, les verbalisations contestables, ou encore la « traque » des contrevenants, selon le mot fréquemment employé aussi bien par les policiers et gendarmes que par les reporters locaux. Elles font émerger la minorité nécessairement discrète des « réfractaires au confinement », celles et ceux qui ont continué à fréquenter les zones interdites malgré la présence policière. Après de premiers coups de sonde fructueux, l'investigation a pris un tour systématique, ce qu'internet rend désormais possible : armés de quelques mots clés (« confinement », « contrôles », mais aussi « barbecue » ou « drones »), nous avons interrogé un moteur de recherche pour chaque département métropolitain, et pour la période allant du 16 mars au 30 mai 2020. Ces histoires, qui pour la plupart ne dépassent pas 500 mots, ont tout de petites fables de circonstance, mettant en scène les dangers que présentent les transgressions du confinement.

Elles renseignent sur au moins trois choses qui nous intéressent au premier chef. Ce sont d'abord les moyens mis en œuvre pour la surveillance de la population. Grâce à elles, nous avons pu documenter l'usage systématique des drones, des hélicoptères et des caméras de surveillance. Ensuite, elles montrent qu'un certain nombre de personnes ont continué à braver les interdits tout au long du confinement. Enfin, elles documentent la politique de communication des autorités et ses relais médiatiques. C'est naturellement le cas lorsque les policiers et gendarmes font leur propre publicité, ou lorsque tel maire vante l'action de sa police municipale. Souvent, il s'agit d'informer en même temps que d'inquiéter en répétant la leçon, comme dans les Pyrénées-Orientales où la gendarmerie publie sur sa page *Facebook*, le 24 mars, une carte de son quadrillage du territoire -- les points de contrôle fixes -- accompagnée du commentaire suivant : « Le groupement de gendarmerie départementale des Pyrénées-Orientales est plus que jamais mobilisé, PARTOUT et TOUT LE TEMPS, pour vous protéger, pour assurer l'intégrité des biens et pour vérifier que vous RESTEZ CHEZ VOUS [@t.2020] ». Parfois, les forces de l'ordre préfèrent simplement mettre en scène leur quotidien, comme dans la série « Bleu » dont les gendarmes de Dordogne diffusent le premier épisode le 4 avril sur leur chaîne Youtube[@g.2020b]. Ailleurs encore, elles commentent leurs succès sur les réseaux sociaux, voire profitent des drones et hélicoptères utilisés au quotidien pour filmer les beautés de la France (vide) vue du ciel -- voir par exemple le film réalisé par la Préfecture de Police pour Paris[@bxr.2020]. Très souvent, elles ont pu alors s'appuyer sur la presse locale pour relayer leur message, tout particulièrement dans le cadre d'innombrables publireportages dans lesquels le journaliste « *embeded* » les montrait au travail, sur terre ou dans les airs, en train de surveiller et de contrôler celles et ceux qui s'aventuraient encore dans l'espace public. L'article publié dans le *Berry Républicain* le 2 avril est en ce sens exemplaire. Le localier est invité à assister au premier déploiement de drone dans le ciel de la Préfecture du Cher, en présence de la directrice départementale de la sécurité publique. Sous l'ensemble des images et de la vidéo qui illustrent l'article, le « crédit photographique » indique : « SRPJ Orléans »[@letreulle2020].

Comme on a pu le constater dans les pages qui précèdent, nombre de quotidiens ou d'hebdomadaires, qu'ils soient nationaux ou régionaux, ne se sont guère écartés de cette ligne de promotion du travail de l'État. A de rares exceptions près (celles d'organes qu'on qualifie, souvent avec une connotation péjorative, de « militants » : *Reporterre*, *Bastamag*, *Rue89*[@gerardin2020] ou le service « CheckNews » de *Libération* par exemple), ils se sont en quelque sorte auto-institués, à l'instar de très nombreuses municipalités, comme relais et bras droit des autorités pour diffuser et rappeler les mesures prises dans le cadre de l'état d'urgence. Une des manifestations les plus frappantes de la couverture médiatique des événements du printemps 2020 tient ainsi à la récurrence de ces reportages réalisés aux côtés des forces de l'ordre.

Ce caractère particulier des sources n'est pas sans intérêt pour qui souhaite comprendre les ressorts du conformisme. De façon quasi unanime, les journaux ont servi de caisse de résonance aux « points presse » officiels, n'interrogeant que très rarement les choix et dispositifs mis en place. D'aucun mentionneront ici, en contrepoint, les quelques articles critiquant l'enlèvement des bancs publics à Béziers ou l'appel aux chasseurs du préfet de Seine et Marne. Mais outre que ces exemples restaient justement présentés comme des cas hors norme, déviants (là ils exagèrent), ils laissent dans l'ombre toutes les fois où des propos étonnants tenus par des préfets, des directeurs de la sécurité publique ou des maires -- on en a lu de nombreux exemples -- ont été relayés tels quels, sans commentaires. En se rangeant parmi les acteurs de la lutte contre la pandémie, les organes de presse n'ont pas peu contribué à rendre invisible sinon indicible toute parole qui viendrait discuter les choix officiels. Ce faisant, ils ont, eux aussi, pris une part non négligeable dans la fabrique du conformisme.