---
title: "Chiffres de la surveillance"
---

Ces différentes sources sont mobilisées tout au long de la seconde partie du livre, celle qui s'intéresse aux logiques de la conformation. Mais, pour enquêter sur l'activité policière, nous avions besoin d'autres données, et notamment des chiffres territorialisés des verbalisations et des contrôles. En la matière la situation est contrastée. Pour ce qui concerne les amendes, les données par département sont systématiques puisque nous disposons des chiffres enregistrés par l'Agence Nationale de Traitement Automatisé des Infractions (ANTAI), et tardivement rendus publics grâce à l'opiniâtreté d'un journaliste indépendant[@lechenet2021].

En revanche, nous ne disposons pas d'une distribution départementale équivalente pour ce qui concerne les totalisations des contrôles, les services du Ministère de l'Intérieur ne les ayant jamais rendues publiques. Or ces données des contrôles sont a priori les plus importantes au sens où, comme on l'a vu, c'est l'universalité potentielle des vérifications, plus que l'importance des amendes, qui constitue la véritable « nouveauté » induite par le confinement en matière d'ordre public. Pour résorber ce manque, nous avons déployé d'importants efforts pour rassembler les chiffres livrés dans la presse ou sur les réseaux sociaux, au printemps 2020, par les préfectures et les mairies qui avaient alors fait le choix de « communiquer ». Grâce à ce travail, nous disposons, au terme de la récolte, d'une solide base de données rassemblant les chiffres des vérifications rendus publics pour la gendarmerie, la police nationale et la police municipale, ensemble ou séparément, à différentes dates et pour 22 villes et 60 départements de métropole. Ces chiffres montrent d'impressionnantes différences de traitement selon les territoires. Certaines sont relativement attendues. Il aurait été pour le moins bizarre de s'acharner à verbaliser les habitants de la Lozère, par exemple. D'autres posent davantage de questions.

L'étude de l'activité des forces de l'ordre a également bénéficié de l'apport d'une enquête menée à l'automne 2020 par une chercheuse au Centre de Recherches sur le Droit et les Institutions Pénales, Marion Guénot, que nous remercions chaleureusement pour son aide précieuse. L'étude visait à comprendre en quoi le confinement avait transformé les pratiques quotidiennes des forces de l'ordre. En acceptant avec gentillesse de mettre ses données (non encore publiées) à notre disposition (entretiens et résultats d'un questionnaire diffusé en interne), notre collègue nous a permis de retourner le miroir de notre propre enquête en accédant au regard portés par les policiers eux-mêmes sur les tâches de surveillance de la présence humaine dans l'espace public qui constituaient alors l'essentiel de leur activité.